// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/polls": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of polls with optional filtering and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Get polls",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "example": 20,
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "technology",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "userID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of polls",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_delivery_http_pollhandler.GetPollsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new poll with title, options, and tags",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Create a new poll",
                "parameters": [
                    {
                        "description": "Poll creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_pollhandler.CreatePollRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Poll created successfully"
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/polls/{id}/skip": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mark a poll as skipped for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Skip a poll",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Skip request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_pollhandler.SkipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Poll skipped successfully"
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Already skipped",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/polls/{id}/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get voting statistics for a specific poll",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Get poll statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Poll statistics",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_pollhandler.GetPollStatsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/polls/{id}/vote": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit a vote for a specific option in a poll",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polls"
                ],
                "summary": "Vote on a poll",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vote request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_pollhandler.VoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vote recorded successfully"
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Already voted",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/pollapp_pkg_errors.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_delivery_http_pollhandler.CreatePollRequest": {
            "description": "CreatePollRequest represents the request for creating a poll",
            "type": "object",
            "required": [
                "options",
                "tags",
                "title"
            ],
            "properties": {
                "options": {
                    "type": "array",
                    "maxItems": 10,
                    "minItems": 2,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['Go'",
                        " 'Python'",
                        " 'JavaScript']"
                    ]
                },
                "tags": {
                    "type": "array",
                    "maxItems": 5,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['technology'",
                        " 'programming']"
                    ]
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 3,
                    "example": "What's your favorite programming language?"
                }
            }
        },
        "internal_delivery_http_pollhandler.GetPollStatsResponse": {
            "description": "GetPollStatsResponse represents the response for getting poll statistics",
            "type": "object",
            "properties": {
                "pollId": {
                    "type": "integer",
                    "example": 1
                },
                "totalVotes": {
                    "type": "integer",
                    "example": 100
                },
                "votes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_delivery_http_pollhandler.Vote"
                    }
                }
            }
        },
        "internal_delivery_http_pollhandler.GetPollsResponse": {
            "description": "GetPollsResponse represents the response for getting polls",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['Go'",
                        " 'Python'",
                        " 'JavaScript']"
                    ]
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['technology'",
                        " 'programming']"
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "What's your favorite programming language?"
                }
            }
        },
        "internal_delivery_http_pollhandler.SkipRequest": {
            "description": "SkipRequest represents the request for skipping a poll",
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_delivery_http_pollhandler.Vote": {
            "description": "Vote represents vote statistics for a single option",
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 50
                },
                "option": {
                    "type": "string",
                    "example": "Go"
                }
            }
        },
        "internal_delivery_http_pollhandler.VoteRequest": {
            "description": "VoteRequest represents the request for voting on a poll",
            "type": "object",
            "required": [
                "optionIndex",
                "userId"
            ],
            "properties": {
                "optionIndex": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                },
                "userId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "pollapp_pkg_errors.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Poll API",
	Description:      "API for managing polls and votes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
